---
  apiVersion: v1
  kind: Service
  metadata:
    name: mobile-simulator-service
    labels:
      app: mobile-simulator
  spec:
    ports:
      - port: 80
        protocol: TCP
        targetPort: 8080
    type: LoadBalancer
    selector:
      app: mobile-simulator
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mobile-simulator-deployment
  labels:
    app: mobile-simulator
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mobile-simulator
    spec:
      containers:
        - image: anthonyamanse/mobile-simulator:example-bank-1.0
          imagePullPolicy: Always
          name: mobile-simulator
          envFrom:
            - secretRef:
                name: mobile-simulator-secrets
          env:
            - name: PORT
              value: '8080'
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Route
metadata:
  name: mobile-simulator-service
spec:
  to:
    kind: Service
    name: mobile-simulator-service

