apiVersion: batch/v1
kind: Job
metadata:
  name: cc-schema-load
  labels:
    app: cc-schema-load
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cc-schema-load
          image: docker.io/ykoyfman/db-load-icd
          imagePullPolicy: Always
          envFrom:
            - secretRef:
                name: bank-db-secret
